
//Update Contact Email  to dummy email
//String Str ; 
//Contact dummyContact = new Contact();

/*
List<Contact> dummyEmailContacts = new List<Contact>();

dummyEmailContacts = [ SELECT firstname, lastname, email FROM Contact where email != null ];
for(Contact con : dummyEmailContacts){
    con.Email = 'Dummy' + con.Email  ;
}
update dummyEmailContacts;
*/

//ContactService cs = new ContactService();
//cs.removeDummyEmail();